version: '3'
services:
  # Create frontend container
  client: # Name of our service
    build: ./client # path to dockerfile
    ports: # Port binding to host from docker container
      - "5001:5001" # Bind port 3000 of host to 3000 of container
    container_name: safeguardian-client
    restart: always # What to do if container crashes
    links:
      - server
  # Create server container
  server:
    # Create server container  
    build: ./server
    ports:
      - "3011:3011"
    container_name: safeguardian-server
    restart: always
    links:
      - db
  # Create database container
  db:
    image: postgres:11.6-alpine
    ports:
    - "5432:5432"
    container_name: safeguardian-db
    restart: always